name: OrleansCommands
version: '1.0-SNAPSHOT'
main: com.orleansmc.commands.OrleansCommands
api-version: '1.21'
authors: [ MustqfaCan ]
depend:
  - helper
  - OrleansMC
  - SkinsRestorer
permissions:
  "orleansmc.commands.*":
    description: Allows access to all OrleansMC commands
    default: op
  "orleansmc.commands.craftingtable":
    description: Allows access to the /craftingtable command
    default: op
  "orleansmc.commands.enchantingtable":
    description: Allows access to the /enchantingtable command
    default: op
  "orleansmc.commands.promotion":
    description: Allows access to the /promotion command
    default: op